Implemented anticheat mechanism
elpozewaunig/PrisonersDilemma pull request #1
Opened 2024-06-24 09:02 UTC by elpozewaunig

Strategies can no longer directly "see" each other, the only valid opponent identification is through their behaviour.

The anticheat mechanism works by:

- Calling strategies through an `AnonymizedStrategy` wrapper class that passes on method calls to the respective strategies (which are only private accessible)
- Providing competing strategies with a different `GameState` containing an anonymized version of their opponents
- Throwing an exception if the anonymous strategy is incorrectly instantiated

Notably, this affects `WurzerStrategy`. Weirdly enough, it performs slightly better with its cheating mechanism disabled.

@towurzer Any thoughts? Can we still cheat with this? Should we even implement an anticheat? (Kinda loved the cheating approach XD)

2024-06-24 14:10 UTC, towurzer commented
@elpozewaunig 
The Idea itself is interesting and promising, but we should not change it because it would break some strategies (mine for example). But still, if this should be reusable, introducing some antiCheat is a good idea. Why not leave it to some settings where you can set a flag, whether you want to activate antiCheat. That would be a trade-off that I would be more than happy to accept.


Still, in its current state, there are some problems with the current antiCheat. 
To Clone the Opponent, you don't need the class itself. An instance, even if it's wrapped, is enough. You can just clone this wrapped object since the wrapped object will be cloned with this too. 
The adapted cloning command [WurzerStrategy; line99] would be:

- opponents[i] = (GameStrategy) otherPlayer.getClass().getConstructors()[1].newInstance(otherPlayer)

![Screenshot 2024-06-24 160528](https://github.com/elpozewaunig/PrisonersDilemma/assets/98081576/e8278e02-062c-48e6-9eac-f1b55aa72adf)

-------------------------------------------------------------------------------------------------------------------------------------------
By the way: My strategy (in it's current state) performs better with anticheat turned on, because of the fact that I default to TitForTat with round counting, which leads to more points whe playing against a strategy that has a low percentage of acting random.

2024-06-24 14:12 UTC, towurzer requested changes
See comment: 

https://github.com/elpozewaunig/PrisonersDilemma/pull/1#issuecomment-2186676564

2024-06-25 11:35 UTC, elpozewaunig commented
> Still, in its current state, there are some problems with the current antiCheat.
To Clone the Opponent, you don't need the class itself. An instance, even if it's wrapped, is enough. You can just clone this wrapped object since the wrapped object will be cloned with this too.

This is exactly why I'm terrified of you XD. Jokes aside, I was pretty much expecting there to be workarounds and I'll look into patching more of these exploits. Thanks for the insights!

> Why not leave it to some settings where you can set a flag, whether you want to activate antiCheat.

I think that's a good idea. Is just a boolean variable fair enough for this?

2024-06-26 12:08 UTC, elpozewaunig commented
@towurzer I just pushed an update which should make cheating impossible now. Turns out we were just overcomplicating things! Since we already split up the game state into two versions for anonymity, there's no need to contain the opponent strategy object in a `GameState` at all (since the only reason the objects are in the `GameState` are for self-identification). I've replaced it with a dummy strategy that at no point has any information about the strategy it has been exchanged for and throws an exception when `playRound` is called on it.

In theory we could get rid of the opponent strategy in the `GameState` entirely (so that the playing strategy is always player1) but that would break compatibility with the way strategies currently work, and student strategies could no longer just be copy-pasted into this repo.

Side note: 
> You can just clone this wrapped object since the wrapped object will be cloned with this too.

`(GameStrategy) otherPlayer.getClass().getConstructors()[1].newInstance(otherPlayer)` doesn't actually clone the strategy in the wrapper but wraps the current wrapper in another one, which still relays calls to `playRound` to the original strategy, tampering with the actual strategy rather than creating clean copies. That's not optimal but it was also still possible before, since it's functionally equivalent to just calling `playRound` on the opponent strategy (which was your initial approach).

Reflection still makes it possible to access the private `strategy` field of the wrapper (I tried it and it worked), so this should be the cleanest solution without lots of overrides, detections, etc.

2024-06-26 12:24 UTC, elpozewaunig commented
The anticheat can be turned off now by changing the default value in the `GameRunner` constructor. Should be good to go now!

2024-07-08 14:06 UTC, elpozewaunig commented
One additional question for @towurzer and @w0lphi (since you proposed this feature ;)): What should the default configuration for `anticheat` in `Main.java` be? On or off?

2024-07-08 19:23 UTC, towurzer approved these changes
First of All, I'm Sorry that it took that long to review the changes, but you know, exam Season was right around the corner. 

To be honest. I think the solution you implemented, right now, is foolproof. Bold claims, but how do you want to predict a strategy that just throws you an error. 

The implementation of the AnonymousStrategy is spotless and by far the best solution. Since it keeps the project downwards compatible. (as you already pointed out)
Furthermore, I think it's the way to go to throw an exception instead of manipulating the strategy by leading them to believe, their opponent is going to defect no matter what. Since that would be a "tampering" (as you called it in your exception method) with the strategy itself. Which is not what we are trying to achieve. 
The current solution rewards clean code that also handles if something goes wrong, which is always likely whilst cheating. (And yes, I partly say that because my Strategy would be dead otherwise ;). But still ...)

Oh, and I think it's a nice Idea to make the AntiCheat an Opt-in solution, because it supports creative solutions and own Ideas instead of just copying online strategies, since this game got analyzed countless times before.

Regarding the clone of the wrapped object as in Version #1 :
You correctly pointed out that the cloned object would hold the same reference in regard to the Strategy, which could lead to unexpected outcomes. Gandi for example would explode immediately, but other strategies, would just continue and might continue to be vulnerable to exploitation. And as sketchy as reflection is, as powerful is it, as you will have seen whilst testing...
Therefore, the current Solution is definitely an upgrade that makes the antiCheat work (all the time).

I will try to find a way around it, but don't expect much. It seems well engineered.

2024-07-08 20:09 UTC, elpozewaunig commented
> First of All, I'm Sorry that it took that long to review the changes, but you know, exam Season was right around the corner.

No worries, I'm all too aware of the horrors we had to endure XD

> To be honest. I think the solution you implemented, right now, is foolproof. Bold claims, but how do you want to predict a strategy that just throws you an error.

Bold claims indeed, but you confirming the fix offers me some peace of mind that we've at least patched this method of cheating ;).

> Oh, and I think it's a nice Idea to make the AntiCheat an Opt-in solution, because it supports creative solutions

I fully agree! It shifts the goal posts a little but it does make the tournaments a little more spicy and original, which I'm a fan of.

> I will try to find a way around it, but don't expect much. It seems well engineered.

The only way I can currently see this particular method being circumvented would be if there was a way to get the object reference of the caller object (`GameRunner`) through the StackTrace and then use reflection on that object to access its private `player1` and `player2` fields. From what I've found through a quick Google search, this seems not to be possible in Java though. Well, at least not if you don't gain direct access to memory and dig through that, and then our anticheat would actually have to prevent kernel access... I don't think we'll go quite as far XD.

2024-07-08 20:11 UTC, elpozewaunig commented
@towurzer @w0lphi Last question before I think we're good to merge this PR: Should we disable the anticheat by default? Currently it's enabled in `Main.java`.

2024-07-18 21:53 UTC, merged